// Mocks generated by Mockito 5.0.0-nullsafety.7 from annotations
// in fsm2/test/cleaning_air_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:fsm2/src/types.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

import 'watcher.dart' as _i2;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [Watcher].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatcher extends _i1.Mock implements _i2.Watcher {
  MockWatcher() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> onEnter(Type? t, _i4.Event? e) =>
      (super.noSuchMethod(Invocation.method(#onEnter, [t, e]),
          returnValue: Future.value(null),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<void> onExit(Type? t, _i4.Event? e) =>
      (super.noSuchMethod(Invocation.method(#onExit, [t, e]),
          returnValue: Future.value(null),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  void log(String? message) =>
      super.noSuchMethod(Invocation.method(#log, [message]),
          returnValueForMissingStub: null);
}
