// Mocks generated by Mockito 5.0.0 from annotations
// in fsm2/test/mock_watcher.dart.
// Do not manually edit this file.

// generated code.
// ignore_for_file: inference_failure_on_instance_creation

import 'dart:async' as i3;

import 'package:fsm2/src/types.dart' as i4;
import 'package:mockito/mockito.dart' as i1;

import 'watcher.dart' as i2;

// generated code
// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [Watcher].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatcher extends i1.Mock implements i2.Watcher {
  MockWatcher() {
    i1.throwOnMissingStub(this);
  }

  @override
  i3.Future<void> onEnter(Type? t, i4.Event? e) =>
      (super.noSuchMethod(Invocation.method(#onEnter, [t, e]),
          returnValue: Future.value(),
          returnValueForMissingStub: Future<void>.value()) as i3.Future<void>);
  @override
  i3.Future<void> onExit(Type? t, i4.Event? e) =>
      (super.noSuchMethod(Invocation.method(#onExit, [t, e]),
          returnValue: Future.value(),
          returnValueForMissingStub: Future<void>.value()) as i3.Future<void>);
  @override
  void log(String? message) =>
      super.noSuchMethod(Invocation.method(#log, [message]),
          returnValueForMissingStub: null);
}
