#! /usr/bin/env dcli

import 'dart:io';
import 'package:dcli/dcli.dart';
import '../test/registration_test.dart';

/// dcli script generated by:
/// dcli create gen_smcat.dart
///
/// See
/// https://pub.dev/packages/dcli#-installing-tab-
///
/// For details on installing dcli.
///

void main(List<String> args) {
  final machine = createMachine();
  machine.export('registration.smcat');
}

void showUsage(ArgParser parser) {
  // ingore: avoid_print
  print('Usage: gen_smcat.dart -v -prompt <a questions>');
  // ingore: avoid_print
  print(parser.usage);
  exit(1);
}
