#! /usr/bin/env dcli

import 'dart:io';

import 'package:args/args.dart';

import '../test/registration_test.dart';

/// dcli script generated by:
/// dcli create gen_smcat.dart
///
/// See
/// https://pub.dev/packages/dcli#-installing-tab-
///
/// For details on installing dcli.
///

void main(List<String> args) async {
  final machine = await createMachine();
  machine.export('registration.smcat');
}

// ignore: unreachable_from_main
void showUsage(ArgParser parser) {
  // ignore: avoid_print
  print('Usage: gen_smcat.dart -v -prompt <a questions>');
  // ignore: avoid_print
  print(parser.usage);
  exit(1);
}
